### ISSUE TITLE
 small typo in Release 2021-03-08

### ISSUE THREAD

**Issue by Rodvi** [probml/pml-book#62]
In eq. (20.24) p.651 matrix V should be transposed

**Comment by jmlipman** [comment]
![image](https://user-images.githubusercontent.com/3540650/111907656-fd876580-8a5e-11eb-8ec0-a2527d060377.png)

**Comment by jmlipman** [comment]
I guess that the following sentence does not apply anymore since the latest release moved background material to the main body of the book. (from the release notes, "Moved material from the appendices (except for notation) into the main body, integrating some of the material to improve the flow")

![image](https://user-images.githubusercontent.com/3540650/111910011-4263ca00-8a68-11eb-95bb-06a498f520bb.png)

**Comment by murphyk** [comment]
thanks, all fixed
