### ISSUE TITLE
Book1, Chapter 13.4.3, Potential Typo?

### ISSUE THREAD

**Issue by pond-nj** [probml/pml-book#645]
I am not sure if this is a typo here but I am confused with (13.73).

![Screenshot 2567-06-16 at 16 42 22](https://github.com/probml/pml-book/assets/89643111/6f8e8487-339c-49ca-9efc-0393ccc59079)

Shouldn't it be like this?:

$\frac{\partial L}{\partial x}  = \frac{\partial z}{\partial x} = \frac{\partial \sigma(a)}{\partial a} \cdot \frac{\partial Wx}{\partial x} = diagonal\textunderscore matrix \textunderscore of(z(1-z)^T) \cdot W $

**Comment by pond-nj** [comment]
oh, or is it the case that $w$ is a vector and $L=\sigma(w^Tx)$? If it is, that would make sense for me.

**Comment by murphyk** [comment]
You are right. It's suprising no one noticed this before. Also this section was very unclear, since I am computing the Jacobian of the layer, not the gradient of the loss. 
I have rewritten it as shown below. HTH.

<img width="664" alt="Screenshot 2024-06-26 at 9 34 20 PM" src="https://github.com/probml/pml-book/assets/4632336/00c60f7f-189d-4dd6-b076-4c65e9412b3c">
